theme: jekyll-theme-minimal
title: Digital Repair Cafe
description: Digital Repair Cafe is a service of Automatisering Ingest Digitale Archieven (AIDA), operated by meemoo 
logo: https://avatars2.githubusercontent.com/u/56017626