theme: jekyll-theme-minimal
title: AIDA Capture Lab
description: AIDA Capture Lab is a service of Automatisering Ingest Digitale Archieven (AIDA), operated by meemoo 
logo: https://avatars2.githubusercontent.com/u/56017626
