theme: jekyll-theme-minimal
title: Digital Repair Café
description: Digital Repair Café is a project of Automatisering Ingest Digitale Archieven. 
logo: https://avatars2.githubusercontent.com/u/56017626