theme: jekyll-theme-minimal
title: Digital Repair Cafe
description: Digital Repair Cafe is a project of Automatisering Ingest Digitale Archieven. 
logo: https://avatars2.githubusercontent.com/u/56017626